//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMarketing_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        public int cart_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> pro_id { get; set; }
        public string pro_name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string AddedOn { get; set; }
        public Nullable<bool> CartPro_Status { get; set; }
    
        public virtual tbl_product tbl_product { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
