//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMarketing_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orderDetails
    {
        public int orderdetails_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> prod_id { get; set; }
    
        public virtual tbl_order tbl_order { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
